# Generated by Django 5.1.3 on 2024-12-09 14:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание события:')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать событие')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Отображать в главном блоке')),
                ('event_image', models.ImageField(null=True, upload_to='event_imgs', verbose_name='Изображение для Events')),
                ('event_content_image', models.ImageField(null=True, upload_to='content_imgs', verbose_name='Фон для Events')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(help_text='Вы можете использовать HTML или стилизовать текст с разными цветами.')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст новости:')),
                ('news_image', models.ImageField(null=True, upload_to='news-imgs', verbose_name='Изображение для новости')),
                ('content_image', models.ImageField(null=True, upload_to='content_imgs', verbose_name='Фон для блока новости')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать новость')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Отображать в главном блоке')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=255, verbose_name='Название обновления')),
                ('content', models.TextField(verbose_name='Описание обновления:')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать обновление')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Отображать в главном блоке')),
                ('update_image', models.ImageField(null=True, upload_to='update_imgs', verbose_name='Изображение для новости')),
                ('update_content_image', models.ImageField(null=True, upload_to='content_imgs', verbose_name='Фон для блока новости')),
            ],
        ),
    ]
