# Generated by Django 5.1.3 on 2024-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content_imgs', verbose_name='Фон для Events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_imgs', verbose_name='Изображение для Events'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content_imgs', verbose_name='Фон для блока новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='news-imgs', verbose_name='Изображение для новости'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content_imgs', verbose_name='Фон для блока новости'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_image',
            field=models.ImageField(blank=True, null=True, upload_to='update_imgs', verbose_name='Изображение для новости'),
        ),
    ]
