# Generated by Django 5.1.3 on 2024-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_event_content_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_image',
            field=models.ImageField(null=True, upload_to='news_imgs', verbose_name='Фон для блока новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(null=True, upload_to='content_image', verbose_name='Изображение для новости'),
        ),
    ]
