# Generated by Django 5.1.3 on 2024-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content_imgs', verbose_name='Изображение для контента'),
        ),
    ]
