# Generated by Django 5.1.3 on 2024-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='background_image',
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(null=True, upload_to='news-imgs', verbose_name='Изображение для новости'),
        ),
    ]
