# Generated by Django 5.1.3 on 2024-11-30 13:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_highlight_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='highlight_color',
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст новости:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=ckeditor.fields.RichTextField(help_text='Вы можете использовать HTML или стилизовать текст с разными цветами.'),
        ),
    ]
