# Generated by Django 5.1.3 on 2024-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_news_highlight_color_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать новость'),
        ),
    ]
