# Generated by Django 5.1.3 on 2024-11-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event-imgs', verbose_name='Изображение для события')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать событие')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название обновления')),
                ('content', models.TextField(verbose_name='Описание обновления')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='update-icons', verbose_name='Иконка для обновления')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать обновление')),
            ],
        ),
    ]
