# Generated by Django 5.1.3 on 2024-11-30 19:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание события:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default-event.png', null=True, upload_to='event-imgs', verbose_name='Изображение для события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(verbose_name='Описание обновления:'),
        ),
        migrations.AlterField(
            model_name='update',
            name='icon',
            field=models.ImageField(blank=True, default='default-update.png', null=True, upload_to='update-icons', verbose_name='Иконка для обновления'),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Название обновления'),
        ),
    ]
