# Generated by Django 5.1.3 on 2024-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_description_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event-content-imgs', verbose_name='Фоновое изображение'),
        ),
        migrations.AddField(
            model_name='update',
            name='update_image',
            field=models.ImageField(blank=True, null=True, upload_to='update-content-imgs', verbose_name='Фоновое изображение'),
        ),
    ]
