# Generated by Django 5.1.3 on 2024-11-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_event_image_remove_update_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_content_image',
        ),
        migrations.RemoveField(
            model_name='update',
            name='update_content_image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default-event.png', null=True, upload_to='event-imgs', verbose_name='Изображение для события'),
        ),
        migrations.AddField(
            model_name='update',
            name='icon',
            field=models.ImageField(blank=True, default='default-update.png', null=True, upload_to='update-icons', verbose_name='Иконка для обновления'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event-content-imgs', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_image',
            field=models.ImageField(null=True, upload_to='content_imgs', verbose_name='Изображение для блока новости'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_image',
            field=models.ImageField(blank=True, null=True, upload_to='update-content-imgs', verbose_name='Фоновое изображение'),
        ),
    ]
