# Generated by Django 5.1.3 on 2024-12-01 21:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_event_is_featured_news_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст новости:'),
        ),
    ]
